const IMG={r1:"assets/routes/heathrow-london.webp",r2:"assets/routes/gatwick-brighton.webp",r3:"assets/routes/stansted-london.webp",r4:"assets/routes/luton-london.webp",m1:"assets/routes/heathrow-london.webp",m2:"assets/routes/stansted-london.webp",m3:"assets/routes/gatwick-brighton.webp"};
const $=s=>document.querySelector(s),T={LHR:["Terminal 2","Terminal 3","Terminal 4","Terminal 5"],LGW:["North","South"],STN:["Main terminal"],LTN:["Main terminal"],LCY:["Main terminal"]};
const A=[["LHR","Heathrow"],["LGW","Gatwick"],["STN","Stansted"],["LTN","Luton"],["LCY","City"]];
const ROUTES=[["r1","Heathrow (LHR) → Central London",6,"LHR","Central London"],["r2","Gatwick (LGW) → Central London",8,"LGW","Central London"],["r3","Stansted (STN) → Canary Wharf",10,"STN","Canary Wharf"],["r4","Luton (LTN) → Wembley",8,"LTN","Wembley"]];
const MODES=[["m1","Bus & Coach","Great value, frequent services",6,"🚌"],["m2","Train","Fast and direct into London",12,"🚆"],["m3","Taxi & Private Transfer","Door-to-door comfort",45,"🚕"]];
$("#rt").innerHTML=ROUTES.map((r,i)=>`<button class="card" data-i="${i}"><div class="ph"><img src="${IMG[r[0]]}" alt=""><span class="badge">✈️</span></div><div class="t"><b>${r[1]}</b><div class="row"><span>From <strong>£${r[2]}</strong></span><span class="arr">→</span></div></div></button>`).join("");
$("#md").innerHTML=MODES.map(m=>`<button class="card mode"><div class="ph"><img src="${IMG[m[0]]}" alt=""></div><div class="t"><b>${m[1]}</b><small>${m[2]}</small><div class="row"><span>From <strong>£${m[3]}</strong></span><span class="arr">→</span></div></div></button>`).join("");
$("#chips").innerHTML=A.map(a=>`<button class="chip" data-a="${a[0]}" aria-pressed="${a[0]=="LHR"}">✈️ ${a[1]}<small>${a[0]}</small></button>`).join("");
function terms(){$("#tm").innerHTML=T[$("#ap").value].map(t=>`<option>${t}</option>`).join("");document.querySelectorAll(".chip").forEach(c=>c.setAttribute("aria-pressed",c.dataset.a==$("#ap").value))}
$("#ap").onchange=terms;terms();const d=new Date(Date.now()+864e5);d.setHours(10,0,0,0);$("#dt").value=new Date(d-d.getTimezoneOffset()*6e4).toISOString().slice(0,16);
document.querySelectorAll(".chip").forEach(c=>c.onclick=()=>{$("#ap").value=c.dataset.a;terms()});document.querySelectorAll("#rt .card").forEach(c=>c.onclick=()=>{const r=ROUTES[c.dataset.i];$("#ap").value=r[3];terms();$("#ds").value=r[4];show();});
const F={LHR:1,LGW:1.3,STN:1.5,LTN:1.3,LCY:.9};function show(){const ap=$("#ap").value,n=+$("#tr").value,f=F[ap],ds=$("#ds").value;const o=[["🚌","Coach","Coach · 55–75 min",Math.round(6*f)*n,"Cheapest"],["🚆","Train","Direct rail · 25–45 min",Math.round(12*f)*n,"Fastest"],["🚕","Black cab / private","Door to door · 40–70 min",Math.round(45*f)+Math.max(0,n-2)*8,""]];$("#results").style.display="block";$("#results").innerHTML=`<h3>${ap} → ${ds}</h3><p>${$("#tm").value} · ${n} traveller${n>1?"s":""} · ${$("#bg").value}</p>`+o.map((x,i)=>`<div class="opt ${i==0?"best":""}"><span class="ic">${x[0]}</span><div><strong>${x[1]}</strong>${x[4]?` <span class="tag">${x[4]}</span>`:""}<small>${x[2]}</small></div><span class="price">£${x[3]}</span><button class="book" type="button">Select</button></div>`).join("");$("#results").scrollIntoView({behavior:"smooth",block:"center"})}
$("#compare").onsubmit=e=>{e.preventDefault();show()};const hd=document.querySelector("header"),mn=$("#mn");mn.onclick=()=>{const o=hd.classList.toggle("open");mn.setAttribute("aria-expanded",o);mn.textContent=o?"✕":"☰"};document.querySelectorAll("#nv a").forEach(a=>a.onclick=()=>{hd.classList.remove("open");mn.textContent="☰";mn.setAttribute("aria-expanded",false)});document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener("click",e=>{const t=document.querySelector(a.getAttribute("href"));if(t){e.preventDefault();t.scrollIntoView({behavior:"smooth",block:"start"})}}));